---
name: cfn_nag
description: Execute cfn_nag against the code in the repository where the GitHub Action workflow is run.
inputs:
  directory-to-scan:
    description: Where cfn_nag_scan should scan for violations (default: root of repo)
    default: .
outputs:
  violations:
    description: Number of violations found in the repo.
runs:
  using: docker
  image: docker://stelligent/cfn_nag:latest
  args:
    - ${{ inputs.directory-to-scan }}
