---
name: cfn_nag
description: >
  Execute cfn_nag against the code in the repository where the GitHub Action
  workflow is run.
inputs:
  directory-to-scan:
    description: >
      Required. Where cfn_nag_scan should scan for violations.
    required: true
outputs:
  violations:
    description: 'Number of violations found in the repo.'
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.directory-to-scan }}
