---
name: cfn_nag
description: Execute cfn_nag against the code in the repository where the GitHub Action workflow is run.
inputs:
  input_path:
    description: 'Where cfn_nag_scan should scan for violations (default is $GITHUB_WORKSPACE).'
    default: '.'
runs:
  using: docker
  image: Dockerfile
  args:
    - -n
    - --input-path
    - ${{ inputs.input_path }}
