---
name: cfn_nag
description: >
  Execute cfn_nag against the code in the repository where the GitHub Action
  workflow is run.
inputs:
  directory-to-scan:
    description: >
      Where cfn_nag_scan should scan for violations. ($GITHUB_WORKSPACE)
    default: '.'
outputs:
  violations:
    description: 'Number of violations found in the repo.'
runs:
  using: docker
  image: Dockerfile
  args:
    - "--input-path ${{ github.workspace }}/${{ inputs.directory-to-scan }}"
